alerts:
- rule: DEPLOYMENT_FAILED
- rule: DOMAIN_FAILED
features:
- buildpack-stack=ubuntu-22
ingress:
  rules:
  - component:
      name: delivery-fish-monorepo
    match:
      path:
        prefix: /
name: monkfish-app
region: sgp
services:
- environment_slug: node-js
  github:
    branch: main
    repo: SWP-Office-Hour/delivery-fish-monorepo
  http_port: 3000
  instance_count: 1
  instance_size_slug: apps-s-1vcpu-0.5gb
  name: delivery-fish-monorepo
  run_command: node main.js
  source_dir: /dist/apps/be-nestjs-app
