name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  actions: read
  contents: read

env:
  HUSKY: 0
jobs:
  pull-request:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Branch Lint
        if: github.event_name == 'pull_request'
        shell: bash
        run: |
          echo running on branch ${{ github.event.pull_request.base_ref }}
          echo merging branch ${{ github.event.pull_request.head_ref }}
          BRANCH_NAME= ${{ github.event.pull_request.head_ref }}
          PATTERN="^(STORY|TASK|BUG|SCRUM|ISSUE)-[0-9]+"
          if [[ ! $BRANCH_NAME =~ $PATTERN ]]; then
            echo "Head branch name '$BRANCH_NAME' is not valid"
            echo "Branch names must include a Jira ticket ID, e.g., PROJ-123-feature-description."
            exit 1
          fi
          echo "Branch name '$BRANCH_NAME' is valid."
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # This enables task distribution via Nx Cloud
      # Run this command as early as possible, before dependencies are installed
      # Learn more at https://nx.dev/ci/reference/nx-cloud-cli#npx-nxcloud-startcirun
      # Uncomment this line to enable task distribution
      # - run: npx nx-cloud start-ci-run --distribute-on="3 linux-medium-js" --stop-agents-after="e2e-ci"

      # Cache node_modules
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - run: npm ci --legacy-peer-deps
      - run: npx cypress install
      - uses: nrwl/nx-set-shas@v4

      # Prepend any command with "nx-cloud record --" to record its logs to Nx Cloud
      # - run: npx nx-cloud record -- echo Hello World
      # Nx Affected runs only tasks affected by the changes in this PR/commit. Learn more: https://nx.dev/ci/features/affected
      # When you enable task distribution, run the e2e-ci task instead of e2e
      - run: npx nx affected -t lint test build e2e
