name: CI

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  actions: read
  contents: read

env:
  HUSKY: 0
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Check out the repository
      - name: Checkout code
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # This enables task distribution via Nx Cloud
      # Run this command as early as possible, before dependencies are installed
      # Learn more at https://nx.dev/ci/reference/nx-cloud-cli#npx-nxcloud-startcirun
      # Uncomment this line to enable task distribution
      # - run: npx nx-cloud start-ci-run --distribute-on="3 linux-medium-js" --stop-agents-after="e2e-ci"
      
      # Step 2: Validate branch name
      - name: Validate branch name
        run: |
          BRANCH_NAME=${{ github.head_ref || github.ref_name }}
          PATTERN="^(STORY|TASK|BUG|SCRUM|PROJ|ISSUE)-[0-9]+(-[a-z0-9._-]+)*$"
          if [[ ! $BRANCH_NAME =~ $PATTERN ]]; then
            echo "❌ Error: Branch name '$BRANCH_NAME' does not contain a valid Jira Task/Story ID."
            echo "✔️  Branch names must include a Jira ticket ID, e.g., PROJ-123-feature-description."
            exit 1
          fi
          echo "✅ Branch name '$BRANCH_NAME' is valid."
          
      # Step 3: Set up Node.js
      # Cache node_modules
      - name: Set up Node.js
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      # Step 4: Install dependencies
      - name: Install dependencies
      - run: npm ci --legacy-peer-deps
      
       # Step 5: Install Cypress
      - name: Install Cypress
        run: npx cypress install

      # Step 6: Set SHAs for Nx
      - name: Set SHAs for Nx
        uses: nrwl/nx-set-shas@v4

      # Step 7: Run Nx affected tasks
      - name: Run Nx Affected Tasks
        run: npx nx affected -t lint test build e2e
